#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/colourdata.h>
#include <wx/colordlg.h>
#include <memory>

class ConfigClass;

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void MainFormClose( wxCloseEvent& event );
		void WxPanel_Repaint( wxUpdateUIEvent& event );
		void ChangeChartColor( wxCommandEvent& event );
		void ChangePointColor( wxCommandEvent& event );
		void ChangeScale( wxScrollEvent& event );
		void ChangePointSize( wxCommandEvent& event );
		void AddError( wxCommandEvent& event );
		void ChangeRegresionType( wxCommandEvent& event );
		void OpenFormFile( wxCommandEvent& event );
		void OpenFromKeyboard( wxCommandEvent& event );
		void Save( wxCommandEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
  void Repaint();
  void UpdateControls();
  ~GUIMyFrame1();
  std::shared_ptr<ConfigClass> cfg;
  wxBitmap m_buffer;
  wxImage m_image;






};

#endif // __GUIMyFrame1__
